# .github/workflows/docker-build.yml
name: Docker Build

# Trigger only on pushes to the main branch
on:
  push:
    branches: [ main ] # Adjust branch name if yours is different (e.g., master)

jobs:
  build-backend:
    name: Build Backend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Optional: Set up Docker Buildx for more advanced build features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the Docker image for the backend
      - name: Build backend image
        run: docker build -t sophiewagstaff48/backend-app:latest ./backend
        # Replace 'myusername' with your Docker Hub username or another identifier
        # The tag ':latest' is common, but you could use commit SHA, etc.

build-frontend:
  name: Build Frontend Docker Image
  runs-on: ubuntu-latest

  steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Build the Docker image for the frontend
    - name: Build frontend image
      run: docker build -t sophiewagstaff48/frontend-app:latest ./frontend
      # Replace 'myusername' with your Docker Hub username or another identifier